name: "Publish to PyPI (manual bump)"
run-name: "Publish to PyPI (@${{ github.actor }})"

on:
  workflow_dispatch:

jobs:
  publish_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install required libraries
        run: python3 -m pip install toml

      - name: Build and publish to PyPI
        uses: JRubics/poetry-publish@v1.17
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
